extraSimbol: []
supportedSuffixes:
- .bat
name: Bat
blockCommentEndSimbol: ''
description: Analyzer for bat scripts ver.1.0
blockCommentStartSimbol: ''
type: BAT
lineCommentSimbol: "^[ \t]*@?[Rr][Ee][Mm](|[ \t\n\r].*)$"
