extraSimbol:
- <(SCRIPT|STYLE)[^>]*>
- </(SCRIPT|STYLE)>
- /*
- '*/'
- //
supportedSuffixes:
- .htm
- .html
name: Html
blockCommentEndSimbol: -->
description: Analyzer for html file ver.1.0
blockCommentStartSimbol: <!--
type: HTML
lineCommentSimbol: ''
