extraSimbol: []
supportedSuffixes:
- .properties
- .yml
- .yaml
name: Properties
blockCommentEndSimbol: ''
description: Analyzer for properties/yaml file ver.1.0
blockCommentStartSimbol: ''
type: SHELL
lineCommentSimbol: "^[ \t]*#.*$"
